name = "LoremIpsum"
uuid = "c409abef-1ebc-4f92-b5e2-61753c65b9a9"
authors = ["Ceco Elijah Maples <mapleselijah9@gmail.com> and Contributors"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
HTTP = "1"
julia = "1.10"

[extras]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["HTTP", "Test"]